const DEFAULT_TOKEN_TTL_SECONDS = 60 * 60 * 2;
const BCRYPT_HASH_PATTERN = /^\$2[aby]\$\d{2}\$/;

function getAuthConfig() {
    // ADMIN_PASS intentionally stores the bcrypt hash, not the raw password.
    const adminUser = process.env.ADMIN_USER;
    const adminPassHash = process.env.ADMIN_PASS;
    const jwtSecret = process.env.JWT_SECRET;
    const configuredTtl = Number.parseInt(process.env.JWT_EXPIRES_IN_SECONDS || "", 10);

    if (!adminUser || !adminPassHash || !jwtSecret) {
        throw new Error("Missing required auth environment variables.");
    }

    if (!BCRYPT_HASH_PATTERN.test(adminPassHash)) {
        throw new Error("ADMIN_PASS must be a bcrypt hash generated by bcryptjs.");
    }

    return {
        adminUser,
        adminPassHash,
        jwtSecret,
        tokenCookieName: "dv_admin_token",
        tokenTtlSeconds: Number.isFinite(configuredTtl) && configuredTtl > 0
            ? configuredTtl
            : DEFAULT_TOKEN_TTL_SECONDS
    };
}

module.exports = {
    getAuthConfig
};
